version: '3.7'

services:
  api: &api
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: soguazu/avl
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./app:/app
    ports:
      - 8001:8001
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5433:5432

  redis:
    image: redis:alpine
    ports:
      - '6399:6379'

  celery:
    <<: *api
    command: celery worker --app=core --loglevel=info --logfile=logs/celery.log
    ports: []
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - api

  celery-beat:
    <<: *api
    command: celery -A core beat -l info
    ports: []
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - celery

  dashboard:
    <<: *api
    command: flower -A core --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5556:5555
    env_file:
      - ./.env
    depends_on:
      - api
      - redis
      - celery

  locust-master:
    image: locustio/locust
    ports:
      - '8099:8089'
    volumes:
      - ./app:/app
    command: -f /app/locustfile.py --master -H http://localhost:8001
    depends_on:
      - api

  locust-worker:
    image: locustio/locust
    volumes:
      - ./app:/app/
    command: -f /app/locustfile.py --worker --master-host locust-master
    depends_on:
      - api

volumes:
  postgres_data: ~
