name: Deploy Development

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Pull from GitHub
        uses: appleboy/ssh-action@master

        with:
          HOST: ${{ secrets.HOST_IP }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          script: cd ${{ secrets.DEV_PATH }} && ls && git pull && docker-compose up --build -d
